include:
  # Metada shared by many jobs
  - local: .gitlab/rules.yml


stages:
  - style-docstring-check
  - upload
  - release


variables:
  MODULE: quantum_nodes
  VERSION: $CI_COMMIT_TAG
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${MODULE}/${VERSION}"


style-docstring-check:
  stage: style-docstring-check

  image: python:latest

  extends:
    - .run_auto

  before_script:
    - pip install pre-commit

  script:
    - pre-commit run --all-files


upload:
  stage: upload

  image: python:latest

  extends:
    - .tag_only

  needs:
    - job: style-docstring-check

  before_script:
    - echo GE_JOB_ID=$CI_JOB_ID >> upload_report.env

  script:
    - apt-get update
    - apt-get install -y zip unzip
    - zip -r ${MODULE} ${MODULE}
    - mv ${MODULE}.zip ${MODULE}_${VERSION//./_}.zip
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" -- upload-file ${MODULE}_${VERSION//./_}.zip ${PACKAGE_REGISTRY_URL}/${MODULE}_${VERSION//./_}.zip

  artifacts:
    reports:
      dotenv: upload_report.env


release:
  stage: release

  image: registry.gitlab.com/gitlab-org/release-cli:latest

  extends:
    - .tag_only

  needs:
    - job: upload
      artifacts: true

  script:
    - echo "Running release job for ${VERSION}"

  release:
    name: "Quantum Nodes ${VERSION}"
    description: "Minimal Blender version required: 2.92"
    tag_name: ${VERSION}
    assets:
      links:
        - name: "Download Quantum Nodes ${VERSION}"
          url: ${PACKAGE_REGISTRY_URL}/${MODULE}_${VERSION//./_}.zip
        - name: "Documentation"
          url: https://quantum-creative-group.gitlab.io/quantum_nodes_manual/
        - name: "Website"
          url: https://quantum-nodes.com/