repos:
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies: [
      "flake8-quotes==3.3.1",
    ]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    args: [
      "*.py *.rst *.md",
    ]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.1.1
  hooks:
  - id: pydocstyle
    exclude: quantum_nodes/lib/quantumblur.py
    args: [
      "-e"
    ]