name: Style check
on:
  pull_request: # Run in pull requests

  workflow_dispatch: # Allow to run this workflow manually

  push:
    tags: # Run when a new release is created
      - "*"
    branches: # Run when there is a push to master
      - "master"

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files
