name: Unit testing
on:
  pull_request: # Run in pull requests

  workflow_dispatch: # Allow to run this workflow manually

  push:
    branches: # Run when there is a push to master
      - "master"

jobs:
  Unit-testing:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        blender-version: ["2.93.11", "3.3.1",]
        os: ["ubuntu-latest", "windows-latest",]
    env:
      BLENDER_CACHE: ${{ github.workspace }}/cache # The place where blender releases are downloaded
      BLENDER_VERSION: ${{ matrix.blender-version }}
    steps:
      - uses: actions/checkout@v2.5.0

      - uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"

      - uses: syphar/restore-virtualenv@v1.2
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - name: Cache Blender release download
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.BLENDER_CACHE }}
          key: ${{ matrix.os }}-blender-${{ matrix.blender-version }}

      - name: Install dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt

      - name: Run test suite (Blender ${{ matrix.blender-version }}, ${{ matrix.os }})
        run: python -m scripts.test -b ${{ matrix.blender-version }} -os ${{ matrix.os }}